name: WP-Stan
description: A custom GitHub Action to run PHPStan on WordPress plugins/themes.
author: TiDschi

inputs:
  phpstan-config:
    description: 'Path to PHPStan configuration file'
    required: false
    default: './phpstan.neon'

  phpstan-level:
    description: 'PHPStan analysis level'
    required: false
    default: 'max'

outputs:
  result:
    description: 'The result of PHPStan analysis'

runs:
  using: "composite"
  steps:
    - name: Run PHPStan with WordPress Rules
      shell: bash
      run: |
        php ./tests/phpstan/bin/phpstan analyse --level=${{ inputs.phpstan-level }} --configuration=${{ inputs.phpstan-config }}
