<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit518f30fac5d8a9a2a7b24dd432da30d7
{
    public static $files = array (
        '9b38cf48e83f5d8f60375221cd213eee' => __DIR__ . '/..' . '/phpstan/phpstan/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SzepeViktor\\PHPStan\\WordPress\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SzepeViktor\\PHPStan\\WordPress\\' => 
        array (
            0 => __DIR__ . '/..' . '/szepeviktor/phpstan-wordpress/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit518f30fac5d8a9a2a7b24dd432da30d7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit518f30fac5d8a9a2a7b24dd432da30d7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit518f30fac5d8a9a2a7b24dd432da30d7::$classMap;

        }, null, ClassLoader::class);
    }
}
